import uuid
from datetime import datetime
from typing import Protocol

from argumenta.domain.accounts import ExamTarget, GoogleIdentity, UserAccount
from argumenta.domain.enums import Exam


class AccountRepository(Protocol):
    def get_by_email(self, email: str) -> UserAccount | None: ...

    def get_by_id(self, user_id: uuid.UUID) -> UserAccount | None: ...

    def create_user(
        self, email: str, nickname: str, terms_accepted_at: datetime
    ) -> UserAccount: ...

    def add_email_identity(self, user_id: uuid.UUID, password_hash: str) -> None: ...

    def add_google_identity(self, user_id: uuid.UUID, subject: str) -> None: ...

    def get_email_password_hash(self, user_id: uuid.UUID) -> str | None: ...

    def find_user_by_google_subject(self, subject: str) -> UserAccount | None: ...


class ExamTargetRepository(Protocol):
    def list_for_user(self, user_id: uuid.UUID) -> list[ExamTarget]: ...

    def active_exam(self, user_id: uuid.UUID) -> Exam | None:
        """Which lens the student reads their corrections in; None until they
        pick a target."""
        ...

    def get(self, user_id: uuid.UUID, target_id: uuid.UUID) -> ExamTarget | None: ...

    def exists(self, user_id: uuid.UUID, exam: Exam, year: int) -> bool: ...

    def add(self, user_id: uuid.UUID, exam: Exam, year: int, is_active: bool) -> ExamTarget: ...

    def soft_delete(self, user_id: uuid.UUID, target_id: uuid.UUID) -> None: ...

    def set_active(self, user_id: uuid.UUID, target_id: uuid.UUID) -> None: ...


class PasswordHasher(Protocol):
    def hash(self, password: str) -> str: ...

    def verify(self, password_hash: str, password: str) -> bool: ...


class GoogleIdentityGateway(Protocol):
    def exchange_code(self, code: str, redirect_uri: str) -> GoogleIdentity: ...


class RateLimiter(Protocol):
    def check(self, key: str) -> bool:
        """Register one attempt for the key; False when over the limit."""
        ...

    def reset(self, key: str) -> None: ...
