"""initial schema DER v0.6

Revision ID: c3127ce63329
Revises:
Create Date: 2026-08-20 14:27:04.401875

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = 'c3127ce63329'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


ENUM_TYPES = (
    "exam",
    "auth_provider",
    "device_platform",
    "content_status",
    "chapter_kind",
    "branch",
    "beat_type",
    "submission_context",
    "verdict",
    "dimension",
    "annotation_type",
    "severity",
    "reaction_beat",
    "chapter_status",
)


def upgrade() -> None:
    # citext for case-insensitive users.email; gen_random_uuid() is core since PG13
    op.execute("CREATE EXTENSION IF NOT EXISTS citext")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('themes',
    sa.Column('exam', sa.Enum('enem', 'fuvest', name='exam'), nullable=False),
    sa.Column('year', sa.SmallInteger(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False, comment='tema real que caiu'),
    sa.Column('statement', sa.Text(), nullable=False, comment='enunciado reescrito'),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_themes'))
    )
    op.create_table('users',
    sa.Column('email', postgresql.CITEXT(), nullable=False),
    sa.Column('nickname', sa.Text(), nullable=False),
    sa.Column('terms_accepted_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index('uq_users_email', 'users', ['email'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_table('auth_identities',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.Enum('google', 'email', name='auth_provider'), nullable=False),
    sa.Column('provider_subject', sa.Text(), nullable=True),
    sa.Column('password_hash', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_auth_identities_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_auth_identities'))
    )
    op.create_index('uq_auth_identities_provider_subject', 'auth_identities', ['provider', 'provider_subject'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_index('uq_auth_identities_user_provider', 'auth_identities', ['user_id', 'provider'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_table('daily_activity',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('activity_date', sa.Date(), nullable=False),
    sa.Column('submissions_count', sa.SmallInteger(), server_default=sa.text('0'), nullable=False, comment='limite diario de 3'),
    sa.Column('approved_count', sa.SmallInteger(), server_default=sa.text('0'), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_daily_activity_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'activity_date', name=op.f('pk_daily_activity'))
    )
    op.create_table('push_devices',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('platform', sa.Enum('ios', 'android', name='device_platform'), nullable=False),
    sa.Column('token', sa.Text(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_push_devices_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_push_devices'))
    )
    op.create_index('uq_push_devices_token', 'push_devices', ['token'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_table('stories',
    sa.Column('theme_id', sa.UUID(), nullable=True, comment='null no tutorial'),
    sa.Column('slug', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('synopsis', sa.Text(), nullable=False),
    sa.Column('position', sa.SmallInteger(), nullable=False, comment='ordem na trilha'),
    sa.Column('is_tutorial', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('dimension_floor', sa.SmallInteger(), nullable=False, comment='piso por dimensao 0-100'),
    sa.Column('min_average', sa.SmallInteger(), nullable=False, comment='media minima 0-100'),
    sa.Column('cover_asset', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('draft', 'published', name='content_status'), server_default='draft', nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['theme_id'], ['themes.id'], name=op.f('fk_stories_theme_id_themes'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_stories'))
    )
    op.create_index('uq_stories_position', 'stories', ['position'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_index('uq_stories_slug', 'stories', ['slug'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_table('user_exam_targets',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('exam', sa.Enum('enem', 'fuvest', name='exam'), nullable=False),
    sa.Column('year', sa.SmallInteger(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_exam_targets_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_exam_targets'))
    )
    op.create_index('uq_user_exam_targets_active_lens', 'user_exam_targets', ['user_id'], unique=True, postgresql_where=sa.text('is_active AND deleted_at IS NULL'))
    op.create_index('uq_user_exam_targets_user_exam_year', 'user_exam_targets', ['user_id', 'exam', 'year'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_table('characters',
    sa.Column('story_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('persona_brief', sa.Text(), nullable=False, comment='voz do personagem para a IA'),
    sa.Column('portrait_asset', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['story_id'], ['stories.id'], name=op.f('fk_characters_story_id_stories'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_characters'))
    )
    op.create_table('chapters',
    sa.Column('story_id', sa.UUID(), nullable=False),
    sa.Column('position', sa.SmallInteger(), nullable=False),
    sa.Column('kind', sa.Enum('confronto', 'chefe', name='chapter_kind'), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('objective', sa.Text(), nullable=False, comment='o que o aluno deve alcancar'),
    sa.Column('antagonist_id', sa.UUID(), nullable=False, comment='quem convencer'),
    sa.Column('min_words', sa.SmallInteger(), nullable=False),
    sa.Column('max_words', sa.SmallInteger(), nullable=False),
    sa.Column('evaluator_brief', sa.Text(), nullable=False, comment='o que e argumento viavel aqui'),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['antagonist_id'], ['characters.id'], name=op.f('fk_chapters_antagonist_id_characters'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['story_id'], ['stories.id'], name=op.f('fk_chapters_story_id_stories'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_chapters'))
    )
    op.create_index('uq_chapters_story_position', 'chapters', ['story_id', 'position'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_table('chapter_beats',
    sa.Column('chapter_id', sa.UUID(), nullable=False),
    sa.Column('branch', sa.Enum('main', 'consequence', 'recovery', name='branch'), nullable=False),
    sa.Column('position', sa.SmallInteger(), nullable=False),
    sa.Column('beat_type', sa.Enum('narration', 'dialogue', 'objective', 'hint', name='beat_type'), nullable=False),
    sa.Column('character_id', sa.UUID(), nullable=True, comment='so em dialogue'),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('illustration_asset', sa.Text(), nullable=True, comment='cena ilustrada'),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapters.id'], name=op.f('fk_chapter_beats_chapter_id_chapters'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], name=op.f('fk_chapter_beats_character_id_characters'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_chapter_beats'))
    )
    op.create_index('uq_chapter_beats_chapter_branch_position', 'chapter_beats', ['chapter_id', 'branch', 'position'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_table('drafts',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('chapter_id', sa.UUID(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapters.id'], name=op.f('fk_drafts_chapter_id_chapters'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_drafts_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'chapter_id', name=op.f('pk_drafts'))
    )
    op.create_table('submissions',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('chapter_id', sa.UUID(), nullable=False),
    sa.Column('attempt_number', sa.SmallInteger(), nullable=False),
    sa.Column('context', sa.Enum('main', 'recovery', name='submission_context'), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('word_count', sa.SmallInteger(), nullable=False),
    sa.Column('typing_ms', sa.Integer(), nullable=True, comment='tempo de escrita'),
    sa.Column('paste_count', sa.SmallInteger(), server_default=sa.text('0'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapters.id'], name=op.f('fk_submissions_chapter_id_chapters'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_submissions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_submissions'))
    )
    op.create_index('ix_submissions_user_chapter', 'submissions', ['user_id', 'chapter_id'], unique=False)
    op.create_index('uq_submissions_user_chapter_attempt', 'submissions', ['user_id', 'chapter_id', 'attempt_number'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_table('chapter_progress',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('chapter_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('locked', 'available', 'drafting', 'in_consequence', 'in_recovery', 'passed', name='chapter_status'), server_default='locked', nullable=False),
    sa.Column('attempts', sa.SmallInteger(), server_default=sa.text('0'), nullable=False),
    sa.Column('passing_submission_id', sa.UUID(), nullable=True),
    sa.Column('unlocked_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('passed_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapters.id'], name=op.f('fk_chapter_progress_chapter_id_chapters'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['passing_submission_id'], ['submissions.id'], name=op.f('fk_chapter_progress_passing_submission_id_submissions'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_chapter_progress_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'chapter_id', name=op.f('pk_chapter_progress'))
    )
    op.create_table('character_reactions',
    sa.Column('submission_id', sa.UUID(), nullable=False),
    sa.Column('character_id', sa.UUID(), nullable=False),
    sa.Column('beat', sa.Enum('rebuttal', 'convinced', 'consequence_intro', 'recovery_prompt', name='reaction_beat'), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('model', sa.Text(), nullable=False),
    sa.Column('prompt_version', sa.Text(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], name=op.f('fk_character_reactions_character_id_characters'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['submission_id'], ['submissions.id'], name=op.f('fk_character_reactions_submission_id_submissions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_character_reactions'))
    )
    op.create_table('evaluations',
    sa.Column('submission_id', sa.UUID(), nullable=False),
    sa.Column('is_current', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('verdict', sa.Enum('approved', 'failed_technical', 'failed_persuasion', name='verdict'), nullable=False),
    sa.Column('average_score', sa.Numeric(precision=5, scale=2), nullable=False, comment='0-100'),
    sa.Column('floor_value', sa.SmallInteger(), nullable=False, comment='piso congelado no envio'),
    sa.Column('min_average', sa.SmallInteger(), nullable=False, comment='media congelada no envio'),
    sa.Column('model', sa.Text(), nullable=False),
    sa.Column('prompt_version', sa.Text(), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('input_tokens', sa.Integer(), nullable=True),
    sa.Column('output_tokens', sa.Integer(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['submission_id'], ['submissions.id'], name=op.f('fk_evaluations_submission_id_submissions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_evaluations'))
    )
    op.create_index('uq_evaluations_current', 'evaluations', ['submission_id'], unique=True, postgresql_where=sa.text('is_current AND deleted_at IS NULL'))
    op.create_table('telemetry_events',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False, comment='identity, alto volume'),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('submission_id', sa.UUID(), nullable=True),
    sa.Column('event_type', sa.Text(), nullable=False, comment='paste, typing_stats, screen_view'),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='unico jsonb do modelo'),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['submission_id'], ['submissions.id'], name=op.f('fk_telemetry_events_submission_id_submissions'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_telemetry_events_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_telemetry_events'))
    )
    op.create_index('ix_telemetry_events_user_created', 'telemetry_events', ['user_id', 'created_at'], unique=False)
    op.create_table('evaluation_annotations',
    sa.Column('evaluation_id', sa.UUID(), nullable=False),
    sa.Column('span_start', sa.Integer(), nullable=False, comment='offset no texto'),
    sa.Column('span_end', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('spelling', 'accentuation', 'punctuation', 'grammar', 'cohesion', 'coherence', 'repertoire_alert', 'repertoire_praise', 'persuasion', name='annotation_type'), nullable=False),
    sa.Column('severity', sa.Enum('error', 'warning', 'praise', name='severity'), nullable=False),
    sa.Column('message', sa.Text(), nullable=False, comment='explicacao curta'),
    sa.Column('suggestion', sa.Text(), nullable=True, comment='forma correta'),
    sa.Column('priority', sa.SmallInteger(), nullable=False, comment='1-3 entra no para passar'),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['evaluation_id'], ['evaluations.id'], name=op.f('fk_evaluation_annotations_evaluation_id_evaluations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_evaluation_annotations'))
    )
    op.create_table('evaluation_scores',
    sa.Column('evaluation_id', sa.UUID(), nullable=False),
    sa.Column('dimension', sa.Enum('norma_culta', 'coesao', 'coerencia', 'repertorio', 'persuasao', 'proposta_intervencao', name='dimension'), nullable=False),
    sa.Column('score', sa.SmallInteger(), nullable=False, comment='0-100'),
    sa.Column('passed_floor', sa.Boolean(), nullable=False),
    sa.Column('evidence', sa.Text(), nullable=False, comment='citacao do texto que sustenta a nota'),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['evaluation_id'], ['evaluations.id'], name=op.f('fk_evaluation_scores_evaluation_id_evaluations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_evaluation_scores'))
    )
    op.create_index('ix_evaluation_scores_dimension', 'evaluation_scores', ['dimension'], unique=False)
    op.create_index('uq_evaluation_scores_evaluation_dimension', 'evaluation_scores', ['evaluation_id', 'dimension'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_evaluation_scores_evaluation_dimension', table_name='evaluation_scores', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index('ix_evaluation_scores_dimension', table_name='evaluation_scores')
    op.drop_table('evaluation_scores')
    op.drop_table('evaluation_annotations')
    op.drop_index('ix_telemetry_events_user_created', table_name='telemetry_events')
    op.drop_table('telemetry_events')
    op.drop_index('uq_evaluations_current', table_name='evaluations', postgresql_where=sa.text('is_current AND deleted_at IS NULL'))
    op.drop_table('evaluations')
    op.drop_table('character_reactions')
    op.drop_table('chapter_progress')
    op.drop_index('uq_submissions_user_chapter_attempt', table_name='submissions', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index('ix_submissions_user_chapter', table_name='submissions')
    op.drop_table('submissions')
    op.drop_table('drafts')
    op.drop_index('uq_chapter_beats_chapter_branch_position', table_name='chapter_beats', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_table('chapter_beats')
    op.drop_index('uq_chapters_story_position', table_name='chapters', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_table('chapters')
    op.drop_table('characters')
    op.drop_index('uq_user_exam_targets_user_exam_year', table_name='user_exam_targets', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index('uq_user_exam_targets_active_lens', table_name='user_exam_targets', postgresql_where=sa.text('is_active AND deleted_at IS NULL'))
    op.drop_table('user_exam_targets')
    op.drop_index('uq_stories_slug', table_name='stories', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index('uq_stories_position', table_name='stories', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_table('stories')
    op.drop_index('uq_push_devices_token', table_name='push_devices', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_table('push_devices')
    op.drop_table('daily_activity')
    op.drop_index('uq_auth_identities_user_provider', table_name='auth_identities', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index('uq_auth_identities_provider_subject', table_name='auth_identities', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_table('auth_identities')
    op.drop_index('uq_users_email', table_name='users', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_table('users')
    op.drop_table('themes')
    # ### end Alembic commands ###
    # autogenerate does not drop the native enum types the tables left behind
    for enum_name in ENUM_TYPES:
        op.execute(f'DROP TYPE IF EXISTS "{enum_name}"')
