"""add last_streak_reminder_at to users

Revision ID: 9dbe20c77d6c
Revises: a1c4d9e77b21
Create Date: 2026-08-25 11:30:08.232548

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9dbe20c77d6c"  # pragma: allowlist secret
down_revision: str | None = "a1c4d9e77b21"  # pragma: allowlist secret
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("last_streak_reminder_at", sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "last_streak_reminder_at")
    # ### end Alembic commands ###
