name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          pip install uv
          uv venv --python=python3.12
          uv sync

      - name: Run pre-commit
        run: |
          source .venv/bin/activate
          pre-commit run --all-files

      - name: Run Pytest
        if: github.event_name != 'pull_request' || !startsWith(github.head_ref, 'release-please--')
        env:
          TERM: dumb
        run: |
          source .venv/bin/activate
          uv run --active pytest
